Basic project
sajjadrajaee/TodoListTest pull request #1
Opened 2022-07-12 12:40 UTC by sajjadrajaee

"To-do list" is a tool that helps to organize our day. It simply lists the things that you need to do and allows you to mark them as complete. I built a simple website that allows for doing that, and you will do it using ES6 and Webpack!

2022-07-12 17:20 UTC, digia3d requested changes
Good job. The code is clean, dry, and follows JavaScript best practices. Some suggestions look in the comment below. :+1:

2022-07-12 17:20 UTC, digia3d commented on src/index.html
> +  <div class="container">
Maybe it will be better to use HTML syntax instead of using only div. For example use header with class "container".

2022-07-12 20:55 UTC, digia3d approved these changes
APPROVED! :100: 
Congratulation :1st_place_medal: 
It is time to merge.

2022-07-13 07:47 UTC, sajjadrajaee commented
Thank you for your time spent reviewing my code. you are right, it's better to use semantic tags. I will fix all changes. 👌

2022-07-13 07:47 UTC, merged